version: '3'

services:
  web:
    build: ./web-static
    ports:
      - "8888:80"
    restart: unless-stopped
    
  api:
    build: ./api
    ports:
      - "9999:3000"
    restart: unless-stopped 